language: python
python:
  - 2.6
  - 2.7
  - 3.2
env:
  - DJANGO=1.4.2
  - DJANGO=1.5b2
install:
  - pip install https://github.com/django/django/archive/${DJANGO}.zip#egg=django
  - pip install -r tests/requirements.txt
  - python setup.py -q install
script: python manage.py test

matrix:
  exclude:
    - python: 3.2
      env: DJANGO=1.4.2