language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.5
  - DJANGO=1.5.1
  - DJANGO=master
install:
  - pip install https://github.com/django/django/archive/${DJANGO}.zip#egg=django
  - pip install -r tests/requirements.txt
  - python setup.py -q install
script:
  - coverage run --source=django_geoip manage.py test
after_success:
  - coveralls --verbose
matrix:
  exclude:
    - python: 3.2
      env: DJANGO=1.4.5
    - python: 3.3
      env: DJANGO=1.4.5
    - python: 3.2
      env: DJANGO=1.3.7
    - python: 3.3
      env: DJANGO=1.3.7
